# Generated by Django 6.0.5 on 2026-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_name'],
            },
        ),
    ]
