# Generated by Django 6.0.5 on 2026-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=100),
            preserve_default=False,
        ),
    ]
