# Generated by Django 6.0.5 on 2026-05-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0003_remove_product_image_url_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images_cdn',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
