# Generated by Django 6.0.5 on 2026-05-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyShop', '0004_alter_product_images_cdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
